require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'LawnQ_SP' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  rn_maps_path = '../node_modules/react-native-maps'

  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'GoogleUtilities'
  pod 'GoogleAppMeasurement'

  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path # <~~ if you need GoogleMaps support on iOS


  target 'LawnQTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
   use_flipper!()
    post_install do |installer|
      react_native_post_install(installer)
      installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  end
end
